### ISSUE TITLE
Android version range issues with version 1.2.88.0

### ISSUE THREAD

**Issue by jkasten2** [googlesamples/unity-jar-resolver#151] opened 2018-09-21 01:28 UTC
## Summary
Since the `1.2.88.0` release there have been issues with this plugin resolving to wrong or higher than expected versions when version ranges are involved between 2 plugins. The problem happens when one plugin requests a version range of an Android native module and another plugin requests an exact version of an Android sub-dependency that was defined in it's POM file. Example PluginA requests a version ranged `firebase-messaging` and PluginB requests an exact version of `play-services-base`. These issues doesn't seem to occur when 2 different plugins are requesting the same exact module.  Below are exact cases reproducing this problem.

## Issue 1
When the upper bound limit symbol is a closing parentheses `)`,  a non-existing version is selected.
**PluginADependencies.xml**
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-messaging:[10.2.1, 15.1.0)"/>
  </androidPackages>
</dependencies>
```

**PluginBDependencies.xml**
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:15.0.1" />
  </androidPackages>
</dependencies>
```

This result in this plugin trying to use `com.google.firebase:firebase-messaging: 15.1.0+.` which results in the following error.

```
Resolve failed due to com.google.firebase:firebase-messaging: 15.1.0+ missing for project :, attempted to use com.google.firebase:firebase-messaging: 15.1.0+, failed due to org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find any version that matches com.google.firebase:firebase-messaging: 15.1.0+.
Versions that do not match:
  - 11.0.4
  - 11.0.2
  - 11.0.1
  - 11.0.0
  - 10.2.6
  - + 30 more
Searched in the following locations:
  - https://maven.google.com/com/google/firebase/firebase-messaging/maven-metadata.xml
```

### Older Versions
In version 1.2.87.0 this error does not occur.

## Issue 2
Same scenarios as issue 1 above, however using `[` instead of `)` for upper bounds the the latest version is used instead of keeping under the limit.

**PluginADependencies.xml**
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.firebase:firebase-messaging:[10.2.1, 15.1.0["/>
  </androidPackages>
</dependencies>
```

**PluginBDependencies.xml**
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:15.0.1" />
  </androidPackages>
</dependencies>
```
This ends up pulling in `com.google.firebase.firebase-messaging-17.3.2.aar` instead of `com.google.firebase.firebase-messaging-15.0.2.aar`.

### Older Versions
In version `1.2.87.0` this version is correctly resolved to `15.0.2`.

## References
This is causing issue #149 as well as https://github.com/OneSignal/OneSignal-Unity-SDK/issues/146

**Comment by stewartmiles** [comment] 2018-09-21 01:38
Hey @jkasten2 , yep I needed to change the way version ranges are handled (see https://github.com/googlesamples/unity-jar-resolver/commit/fff89b8e0ce61f7af37561ba95d74ccb8416c3c4)  - i.e it does not handle maven / ivy version expressions in their entirety - in 1.2.88 so that we can deal with gradle reporting a conflict resolution even though it has correctly selected a valid version to get the latest set of dependencies in Play Services resolving correctly again.

It sounds like somewhere in here, the version expression is getting mangled by the `PackageSpecifier` class resulting in the wrong selection.

**Comment by jkasten2** [comment] 2018-09-21 04:35
@stewartmiles Thanks for the follow up!, thats a ton of changes in that commit! 😮

I have switched to `[` to try limit the upper bounds for now our OneSignal plugin for now to workaround the build error (Issue 1). Getting the limiting to work again (Issue 2) isn't a show stopper like (Issue 1) was for now as our SDK does work with the latest.

Let me know if you need me to test anything or need more details. Thanks.

**Comment by storybell** [comment] 2018-10-26 05:40
After resolving this i get s warning in unity 2017.1.1 f1 , play-service-resolver 1.2.88.0 and macOS.

i used play game service, admob and one signal.

Some conflicting dependencies were found.
The following dependency versions were modified:
com.android.support:customtabs:[26.0.0, 27.2.0[ --> com.android.support:customtabs:27.1.1@aar
com.android.support:support-v4:[26.0.0, 27.2.0[ --> com.android.support:support-v4:27.1.1@aar
com.google.android.gms:play-services-ads:15.0.1 --> com.google.android.gms:play-services-ads:+
com.google.android.gms:play-services-base:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-base:+
com.google.android.gms:play-services-location:[10.2.1, 12.1.0[ --> com.google.android.gms:play-services-location:[10.2.1, 12.1.0[
com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[ --> com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[
com.google.games:gpgs-plugin-support:0.9.50 --> com.google.games:gpgs-plugin-support:+

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__27(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey19:<>m__32()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
Google.RunOnMainThread:Run(Action, Boolean)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__28(Result)
GooglePlayServices.<GradleResolution>c__AnonStorey17:<>m__29(Result)
GooglePlayServices.ProgressReporter:SignalComplete()
GooglePlayServices.ProgressReporter:CommandLineToolCompletion(Result)
GooglePlayServices.<RunAsync>c__AnonStorey2:<>m__3()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAll>m__6()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by chkuang-g** [comment] 2021-03-09 02:12
Seems like the issue is fixed.  Close this issue for now.

**Closed by chkuang-g** 2021-03-09 02:12 UTC
Labels: type: bug
