### ISSUE TITLE
Build fails on Windows with Patch mainTemplate.gradle is enabled

### ISSUE THREAD

**Issue by shiena** [googlesamples/unity-jar-resolver#361] opened 2020-04-17 03:51 UTC
### Please fill in the following fields:
Unity editor version:  2018.4.19f1
External Dependency Manager version: 1.2.151
Source you installed EDM (from .unitypackage or Unity Package Manager): Unity Package Manager
Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
In EDM 1.2.151, the mainTemplate.gradle has a backslash like `"/Assets/GeneratedLocalRepo\framesFirebase/m2repository"`.

```gradle
// Android Resolver Repos Start
([rootProject] + (rootProject.subprojects as List)).each { project ->
    project.repositories {
        def unityProjectPath = $/file:///**DIR_UNITYPROJECT**/$.replace("\\", "/")
        maven {
            url "https://maven.google.com"
        }
        maven {
            url (unityProjectPath + "/Assets/GeneratedLocalRepo\Firebase/m2repository") // Packages/com.google.firebase.app/Firebase/Editor/AppDependencies.xml:20, Packages/com.google.firebase.crashlytics/Firebase/Editor/CrashlyticsDependencies.xml:20, Packages/com.google.firebase.analytics/Firebase/Editor/AnalyticsDependencies.xml:18
        }
        mavenLocal()
        jcenter()
        mavenCentral()
    }
}
// Android Resolver Repos End
```

`Path.Combine` will output the OS native path delimiter on this line.
So further replacement with `FileUtils.PosixPathSeparators` is required.

https://github.com/googlesamples/unity-jar-resolver/blob/v1.2.151/source/VersionHandlerImpl/src/FileUtils.cs#L652

### Please answer the following, if applicable:
100%

**Comment by bassarisse** [comment] 2020-04-17 15:01
Having the same issue.

On this line:
https://github.com/googlesamples/unity-jar-resolver/blob/master/source/VersionHandlerImpl/src/VersionHandlerImpl.cs#L2352

Maybe if could check for `assembly.IsDynamic` before anything, the error would be avoided without resorting to the try/catch?

**Comment by bassarisse** [comment] 2020-04-17 15:03
Sorry, commented on wrong issue.

**Comment by stewartmiles** [comment] 2020-04-17 15:09
Duplicate of #334

**Comment by shiena** [comment] 2020-04-17 15:16
@stewartmiles This is not a duplicate of #334.
#334 is a bug in Unity, but this one is a path combination problem that can be fixed.

**Comment by stewartmiles** [comment] 2020-04-17 15:18
Ah @shiena I missed that in the generated path, looks like it could be a regression caused by ed6e2dbdb5c4ee29a4f1d2213c50a670c4a6a048

**Comment by stewartmiles** [comment] 2020-04-17 15:22
Yep https://github.com/googlesamples/unity-jar-resolver/blob/ed6e2dbdb5c4ee29a4f1d2213c50a670c4a6a048/source/AndroidResolver/src/PlayServicesResolver.cs#L1961

**Comment by shiena** [comment] 2020-04-17 15:22
@stewartmiles  Yes, you can probably fix it with the following difference.

```diff
diff --git a/source/VersionHandlerImpl/src/FileUtils.cs b/source/VersionHandlerImpl/src/FileUtils.cs
index de9e373..1044720 100644
--- a/source/VersionHandlerImpl/src/FileUtils.cs
+++ b/source/VersionHandlerImpl/src/FileUtils.cs
@@ -649,7 +649,7 @@ namespace Google {
             string relativeDir;
             if (GetRelativePathFromAssetsOrPackagesFolder(
                     path, out baseDir, out relativeDir)) {
-                result = Path.Combine(newBase, relativeDir);
+                result = PosixPathSeparators(Path.Combine(newBase, relativeDir));
             }
             return result;
         }
diff --git a/source/VersionHandlerImpl/unit_tests/src/FileUtilsTest.cs b/source/VersionHandlerImpl/unit_tests/src/FileUtilsTest.cs
index dd7d7c7..835bfa5 100644
--- a/source/VersionHandlerImpl/unit_tests/src/FileUtilsTest.cs
+++ b/source/VersionHandlerImpl/unit_tests/src/FileUtilsTest.cs
@@ -390,6 +390,10 @@ namespace Google.VersionHandlerImpl.Tests {
                 FileUtils.ReplaceBaseAssetsOrPackagesFolder(
                     "Foo/Bar", "Assets"),
                 Is.EqualTo("Foo/Bar"));
+
+            Assert.That(
+                FileUtils.ReplaceBaseAssetsOrPackagesFolder(@"Assets\Bar", "Foo"),
+                Is.EqualTo("Foo/Bar"));
         }
     }
 }
```

**Closed** 2020-04-17 22:40 UTC
Labels: type: bug
