### ISSUE TITLE
[Bug] Android Resolver Throws Exception when attempting to Resolve Dependencies and using Custom gradle file

### ISSUE THREAD

**Issue by dioniguerra** [googlesamples/unity-jar-resolver#465] opened 2021-09-21 14:18 UTC
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.11f1
  * External Dependency Manager version: 1.2.166
  * Source you installed EDM4U: Unity Package Manager
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: Firebase
  * Platform you are using the Unity editor on: Mac

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

* Download the Firebase local packages (v8.2.0) from Google Package website (https://developers.google.com/unity/archive#firebase), including the External Dependency Manager for Unity (v1.2.166). 
* Update manifest.json to point to local path for each package.
* In Unity, Resolve Android Dependencies (Assets/External Dependency Manager/Android Resolver/Resolve)
* Once all android dependencies are resolved, enable Custom Main Gradle Template (Project Settings/Player/Publishing Settings/Build/Custom Main Gradle Template), this will generate a mainTemplate.gradle file under Assets/Plugins/Android
* Resolve Android Dependencies to overwrite this new template file, but this is hit with a NullPointerException, see bellow

>Job failed with exception: System.ArgumentException: An empty file name is not valid.
  at System.IO.DirectoryInfo.CheckPath (System.String path) [0x00016] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.IO.DirectoryInfo..ctor (System.String path, System.Boolean simpleOriginalPath) [0x00006] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at System.IO.DirectoryInfo..ctor (System.String path) [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 
  at (wrapper remoting-invoke-with-check) System.IO.DirectoryInfo..ctor(string)
  at Google.FileUtils.CreateFolder (System.String path) [0x0000d] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:630 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at Google.FileUtils.CreateFolder (System.String path) [0x0001b] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:632 
  at GooglePlayServices.PlayServicesResolver.CopyAssetAndLabel (System.String sourceLocation, System.String targetLocation, System.Boolean force) [0x00075] in Z:\tmp\tmp.xL8IU9TsBB\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:2416 
  at GooglePlayServices.GradleTemplateResolver.CopySrcAars (System.Collections.Generic.ICollection`1[T] dependencies) [0x000ae] in Z:\tmp\tmp.xL8IU9TsBB\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:150 
  at GooglePlayServices.GradleTemplateResolver.InjectDependencies (System.Collections.Generic.ICollection`1[T] dependencies) [0x00131] in Z:\tmp\tmp.xL8IU9TsBB\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\GradleTemplateResolver.cs:488 
  at GooglePlayServices.PlayServicesResolver+<ResolveUnsafe>c__AnonStorey9.<>m__1 () [0x00000] in Z:\tmp\tmp.xL8IU9TsBB\third_party\unity\unity_jar_resolver\source\AndroidResolver\src\PlayServicesResolver.cs:1968 
  at Google.RunOnMainThread.ExecuteNext () [0x0003d] in Z:\tmp\tmp.bgjQr7S3O5\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:486 
UnityEngine.Debug:LogError (object)
Google.RunOnMainThread:ExecuteNext () (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:488)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1 () (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction (System.Action) (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:Run (System.Action,bool) (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:472)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe (System.Action`1<bool>,bool,bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1967)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterPromptCheck (System.Action`1<bool>,bool,bool,bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1844)
GooglePlayServices.PlayServicesResolver/<ResolveUnsafeAfterJetifierCheck>c__AnonStorey7:<>m__0 (bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1755)
GooglePlayServices.PlayServicesResolver/<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__1 (GooglePlayServices.PlayServicesResolver/ApiLevelJetifierResult) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2723)
GooglePlayServices.PlayServicesResolver:CheckApiLevelForJetifier (bool,string,System.Action`1<GooglePlayServices.PlayServicesResolver/ApiLevelJetifierResult>) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2687)
GooglePlayServices.PlayServicesResolver/<CanEnableJetifierOrPromptUser>c__AnonStoreyF:<>m__0 (bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2708)
GooglePlayServices.PlayServicesResolver:CheckGradleVersionForJetifier (bool,string,System.Action`1<bool>) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2615)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser (string,System.Action`1<bool>) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2706)
GooglePlayServices.PlayServicesResolver:ResolveUnsafeAfterJetifierCheck (System.Action`1<bool>,bool,bool,bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1752)
GooglePlayServices.PlayServicesResolver/<ScheduleResolve>c__AnonStorey5:<>m__0 () (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1719)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob () (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1576)
GooglePlayServices.PlayServicesResolver:ScheduleResolve (bool,bool,System.Action`1<bool>,bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1732)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve (bool) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2032)
GooglePlayServices.PlayServicesResolver:MenuForceResolve () (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2056)

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)

This happens 100% following the steps bellow on an empty Unity project

What happened? How can we make the problem occur?
NullPointerException, stack trace above

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by paulinon** [comment] 2021-09-22 10:22
Hi @dioniguerra,

Thanks for reporting this issue. Your second steps says to update the manifest.json file. Could you provide more context on how this file is being generated?

If you have a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project, it would be helpful in identifying what's causing this behavior.

**Comment by dioniguerra** [comment] 2021-09-22 11:53
Hi @paulinon, Step 2 follows the following instructions: https://firebase.google.com/docs/unity/setup-alternative, Install Firebase packages using Unity Package Manager

After a number of attempts and brute force, I think I have an idea why this exception happens. It occurs only if you add a package via the Unity Package Manager by path (Package Manager/Add package from disk). I had to uncompress the `com.google.firebase.analytics-8.2.0` package to edit the `AnalyticsDependencies.xml` to use `Firebase/AnalyticsWithoutAdIdSupport` for iOS. This as a result, breaks my Android resolver.  

Any suggestions?

Dioni

**Comment by paulinon** [comment] 2021-09-22 15:04
Thanks for clarifying, @dioniguerra. After performing the steps you've listed, I haven't encountered the exception you described. However, I used version 2020.3.18f1 of the Unity editor. Could you try if updating the editor makes a difference?

**Comment by dioniguerra** [comment] 2021-09-22 21:07
Hi @paulinon yes, I can repro on 2020.3.18f1. I can confirm that in order to repro this exception you need to explore one of the tgz file (decompress it on disk), and add this package from disk, it would look like this on your Packages/manifest.json file:

`{
  "dependencies": {
    "com.google.external-dependency-manager": "file:../GooglePackages/com.google.external-dependency-manager-1.2.166.tgz",
    "com.google.firebase.analytics": "file:../FirebasePackages/com.google.firebase.analytics-8.2.0",
    "com.google.firebase.app": "file:../FirebasePackages/com.google.firebase.app-8.2.0.tgz",
    "com.google.firebase.dynamic-links": "file:../FirebasePackages/com.google.firebase.dynamic-links-8.2.0.tgz",
    "com.google.firebase.messaging": "file:../FirebasePackages/com.google.firebase.messaging-8.2.0.tgz",
    "com.google.firebase.remote-config": "file:../FirebasePackages/com.google.firebase.remote-config-8.2.0.tgz",
...`

In my example I have decompressed and modified the `com.google.firebase.analytics-8.2.0` package

Dioni

**Comment by paulinon** [comment] 2021-09-23 09:00
Hi @dioniguerra,

I haven't made any modifications to any of my packages in my implementation, and the only Firebase product I have there is Analytics. Could you elaborate the extra steps you did before facing the issue? I believe this issue is related to this [ticket](https://github.com/firebase/quickstart-unity/issues/1135) you filed.

**Comment by dioniguerra** [comment] 2021-09-23 14:20
Hi @paulinon I don't believe is related to the issue I raised before, as I can repro this issue in an Empty Unity project. To clarify, the modifications I made to my packages are as follow:

* Download Firebase Analytics package tgz file
* Uncompress this package on disk, and modify the `AnalyticsDependencies.xml` to use `Firebase/AnalyticsWithoutAdIdSupport` instead of `Firebase/Analytics`
* In Unity, add this package from disk via the Package Manager (Package Manager/Add package from disk)
* Enable Custom Gradle template (this will create a mainTemplate.gradle file in Assets/Plugins/Android)
* Resolve Android Dependencies (Assets/External Dependency Manager/Android Resolvers/Resolve)

The desire output is to generate dependencies under the specified GeneratedRepo folder (this is defined in the Android Resolver/Settings), instead it gives NullPointerException with the stack in my original query

Hope this clarifies it a bit, and can help you repro this exception

Dioni

**Comment by paulinon** [comment] 2021-09-27 14:45
Hi @dioniguerra,

I'm unable to perform the third step where you add the package after modifying the `AnalyticsDependencies.xml` file. Could you provide more context on how you were able to achieve this?

Additionally, could you try if modifying the file after importing Firebase Analytics into your project makes a difference? When I did this, I only got this warning after resolving Android dependencies, but no NullPointerException.

<img width="1339" alt="Screen Shot 2021-09-27 at 10 22 14 PM" src="https://user-images.githubusercontent.com/58971522/134931456-b29a59a0-4226-4472-b270-a4200788d5f5.png">

**Comment by dioniguerra** [comment] 2021-10-08 15:09
Hi @paulinon Yes, sorry, I should have been clear, this issue only occurs when Enabling Custom Gradle -which is paramount for our build pipeline in all of our apps. I will try the latest resolved (1.2.167) and get back to you. I am currently using 1.2.166

**Comment by dioniguerra** [comment] 2021-10-14 07:46
Hi @paulinon Sorry for the late reply. I can confirm that the issue still there using latest Resolver Package (1.2.167), See screenshot bellow from Unity Console.

![Screenshot 2021-10-14 at 08 45 38](https://user-images.githubusercontent.com/50740506/137273802-b71fcabc-969f-4fe1-8341-7ebfc9dbbcb6.png)

**Comment by chkuang-g** [comment] 2021-10-19 18:23
Alright, I think EDM4U seems to fail if you use `Add package from disk` option in Unity Package Manager.

I did not turn on `mainTemplate.gradle` and the AndroidResolver would fail due to `ArgumentOutOfRangeException`
```
ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
System.String.Substring (System.Int32 startIndex, System.Int32 length) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.String.Substring (System.Int32 startIndex) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Google.FileUtils.GetPackageDirectory (System.String path, Google.FileUtils+PackageDirectoryType directoryType) (at Z:/tmp/tmp.bgjQr7S3O5/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/FileUtils.cs:451)
GooglePlayServices.GradleResolver.RepoPathToUri (System.String repoPath, System.String sourceLocation) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:178)
GooglePlayServices.GradleResolver.DependenciesToRepoUris (System.Collections.Generic.IEnumerable`1[T] dependencies) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:271)
GooglePlayServices.PlayServicesResolver.GetRepos (System.Collections.Generic.IEnumerable`1[T] dependencies) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2098)
GooglePlayServices.PlayServicesResolver.GradleMavenReposLines (System.Collections.Generic.ICollection`1[T] dependencies) (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2128)
GooglePlayServices.PlayServicesResolver.MenuDisplayLibraries () (at Z:/tmp/tmp.xL8IU9TsBB/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2285)
``` 

I would recommend you to archive the folder back to `.tgz` after you modify `FirebaseAnalyticsDependencies.xml` and use `Add package from tarball` option in Unity Package Manager for now.  `.tgz` is basically `.tar.gz` but with a different extension name.  On mac, you should be able to create the tarball using something like this:
```
tar czf com.google.firebase-8.2.0.tgz path/to/your/package/folder
```

**Comment by dioniguerra** [comment] 2021-10-20 14:46
Hi @chkuang-g 

I didn't get that error you got, as a work around right now I don't turn on `mainTemplate.gradle` and seems to work fine. Anyway, ideally, we need to have custom gradle enable so still looking for a solution. 

I did try to archive the folder back to `.tgz`, however, when importing via Package Manager using tarball I get the following Exception in the Editor, so I am guessing something is wrong in the archive of the folder:

`[Package Manager Window] ENOENT: Cannot cd into '/Users/dioniguerra/Repository/Unity/Firebase Examples/FirebaseTest/Library/PackageCache/.tmp15547dXwE5frHftIM/extract'
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)`

I am using the same command as you have shown, but I first rename the folder back to `package` (as it is when uncompressed), so it looks like this:

`tar czf com.google.firebase.analytics-8.2.0.tgz package/`

There is a different in size from the original tgz downloaded from Firebase download page, so that is why I assumed the `tar` command is wrong. Do you get the same issue?

D

**Comment by chkuang-g** [comment] 2021-11-01 18:52
Ah, yes, all the file should be package under `package/` folder in `.tgz`.  This is what Unity Package Manager expect. Sorry did not made this clearer.

**Closed** 2021-11-19 16:24 UTC
Labels: type: bug
