### ISSUE TITLE
Editor will freeze when using -executeMethod

### ISSUE THREAD

**Issue by mjobin-bhvr** [googlesamples/unity-jar-resolver#389] opened 2020-07-09 12:47 UTC
**Unity editor version:** 2019.1.3f1 and 2019.3.14f1
**External Dependency Manager version:** 1.2.145+
**Source you installed EDM (from .unitypackage or Unity Package Manager):** Issue occurs with both sources
**Features in External Dependency Manager in use (Android Resolver, iOS Resolver, VersionHandler, etc.):** VersionHandler
**Plugins SDK in use (Firebase, Admob, Facebook, etc.):** none
**Platform you are using the Unity editor on (Mac, Windows, or Linux):** Windows
**Platform you are targeting (iOS, Android, and/or desktop):** Doesn't matter
**Scripting Runtime (Mono, and/or IL2CPP):** IL2CPP

The editor will freeze when
- the project is launched using _-executeMethod_, but not _-batchMode_;
- the _Google.VersionHandler.VersionHandlingEnabled_ setting is set to true in GvhProjectSettings.xml.

Since this setting is true by default, installing the package in a project launched this way will freeze the editor. Only workaround in this case is to manually create a GvhProjectSettings.xml file with the _Google.VersionHandler.VersionHandlingEnabled_ setting set to false before installing the package (or kill Unity once it's frozen, then create the settings).

**What's the issue repro rate?** 100%

**Comment by chkuang-g** [comment] 2020-07-09 18:07
This one should be fixed in 1.2.155

https://github.com/googlesamples/unity-jar-resolver/commit/30eaff257bf20ac36a8957ecfd4086a482b53079

**Comment by chkuang-g** [comment] 2020-07-09 18:10
Could you try the latest 1.2.156 and see if it still freeze?

This commit might be related.

https://github.com/googlesamples/unity-jar-resolver/commit/30eaff257bf20ac36a8957ecfd4086a482b53079

**Comment by mjobin-bhvr** [comment] 2020-07-09 18:48
Actually been mostly testing with 1.2.156. Happens since 1.2.145 up to 1.2.156.

**Comment by chkuang-g** [comment] 2020-07-09 19:21
That is definitely odd.  Did you see any error message in your editor log?

Based on the information you provided, you only have EDM4U in your project but no other SDK like Firebase?  Could you provide a sample project to reproduce this issue?

Thank you

**Comment by mjobin-bhvr** [comment] 2020-07-13 17:01
Here is a very minimal Sample Project with the EDM4U v1.2.156 already installed.
[EDM4UIssue389Sample.zip](https://github.com/googlesamples/unity-jar-resolver/files/4913945/EDM4UIssue389Sample.zip)

This command won't freeze the editor:
`Unity.exe -projectPath "<project_path>"`
This one will : 
`Unity.exe -projectPath "<project_path>" -executeMethod "Init.Execute"`

Nothing special in the logs, last lines in the file (just after asset imports) are : 
```
Begin MonoManager ReloadAssembly
Native extension for iOS target not found
Native extension for Android target not found
Native extension for WebGL target not found
Native extension for WindowsStandalone target not found
Refreshing native plugins compatible for Editor in 1.21 ms, found 0 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
```

**Comment by chkuang-g** [comment] 2020-07-16 18:34
@mjobin-bhvr 

I can remove EDM4U and still cause the "freeze".

Based on [Unity documentation](https://docs.unity3d.com/Manual/CommandLineArguments.html)

` To return an error from the command line process, either throw an exception which causes Unity to exit with return code 1, or call EditorApplication.Exit with a non-zero return code. `

So I think you just need to add `EditorApplication.Exit()`

Hope this helps
Shawn

**Comment by mjobin-bhvr** [comment] 2020-07-16 18:48
To be clearer, we are using the executeMethod to call some code on Unity Launch, but the goal is to leave the project opened once that code is executed, and continue working in the project. So calling EditorApplication.Exit() isn't an option here. 

In your test, have you been adding any additionnal command line arguments, for example batchMode? I can confirm using exactly the following command won't freeze without the presence of the EDM4U package.

`Unity.exe -projectPath "<project_path>" -executeMethod "Init.Execute"`

**Comment by mjobin-bhvr** [comment] 2020-07-27 12:12
Any update on this?

**Comment by chkuang-g** [comment] 2020-07-30 19:33
@mjobin-bhvr 

I can confirm the behavior on both Mac and Windows now.

Tried to attach with debugger but did not see any EDM4U APIs in the callstack, on both Windows and Mac.  Still seems like EDM4U's presence trigger something weird in Unity.
`-executeMethod` is a really odd animal.  I mostly see it being used with `--batchmode`, which actually work for this case. Need to investigate its behavior when it is not in batchmode.

Will keep you update.

**Comment by vimanyu** [comment] 2020-08-14 17:19
Hi @mjobin-bhvr, 
As we are still figuring out some oddities in events generated by Unity when '-executeMethod' is supplied, I wanted to point out a simpler workaround than manually editing any files. You could open the editor with a "-gvh_disable" flag and it should disable the version handler for the session. 
Also, are you planning to always open this particular project with "-executeMethod" or is this a one time thing after which you could work on the project without this flag? It will be good to know this because in any of the stated workarounds, version handler is completely disabled for that session.

**Comment by vimanyu** [comment] 2020-08-15 00:33
We have a fix incoming for this in the next release. The issue is that the `EditorApplication.update` event is not reliable when we launch Unity with `-executeMethod` and this was causing one of the callback queues (the one that checks for changes to "Build Target" in Unity) to grow constantly.  We are detecting if `-executeMethod` is supplied and not adding things to this queue. What this also means is if you change the build target in Unity in a session launched with `-executeMethod` method on the command line, version handler will not run automatically. You will have to manually run it.

**Comment by mjobin-bhvr** [comment] 2020-08-17 12:20
Great news! We are looking forward for that fix, and will be confirming it fixes our issue as soon as its released and we can test it.

To answer your questions, we are using -executeMethod each time we launch a project. Also, since we generally prefer running the version handler and resolvers manually, the side effect you mention shouldn't be a problem for us.

**Closed** 2020-09-03 21:35 UTC
Labels: type: bug

**Comment by chkuang-g** [comment] 2020-09-04 00:15
@mjobin-bhvr 

The issue is fixed in this repo but you will need to make the build yourself.  
I'm making a release now and will push it to Githun and UPM soon

**Comment by mjobin-bhvr** [comment] 2020-09-16 13:38
We confirm v. 1.2.159 fixes our issue, thanks a lot!
