### ISSUE TITLE
[BUG] Version Handler - Verbose Logging can't be turned off - console spam

### ISSUE THREAD

**Issue by st4rdog** [googlesamples/unity-jar-resolver#415] opened 2020-11-26 22:29 UTC
Edit: Posted in wrong repo. Moved [here](https://github.com/playgameservices/play-games-plugin-for-unity/issues/2977): 

### [REQUIRED] Please fill in the following fields:
  * Unity editor version: 2019.3.6f1
  * External Dependency Manager version: 1.2.162
  * Source you installed EDM4U: v0.10.12 unitypackage release
  * Features in External Dependency Manager in use: Android Resolver, iOS Resolver, VersionHandler, Package Manager Resolver
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Cannot turn off Verbose Logging for Version Handler. Same as this [issue](https://github.com/googlesamples/unity-jar-resolver/issues/391).

When playing in editor, it will spam the console every time. After turning off Verbose Logging in the settings window, on reopening the window, it will be on again.

Changing the setting in GPGSAndroidSetupUI.cs and NearbyConnectionUI.cs to false doesn't solve it.

I updated from [IronSource's Unity Plugin Version 7.0.3.1](https://developers.ironsrc.com/ironsource-mobile/unity/unity-plugin/#step-1) which came with version 1.2.152.

I extracted the newest version from the unitypackage here, and deleted the older files.

Here is a screenshot of the differences when I unpack the old one:
![ironsource](https://user-images.githubusercontent.com/5329210/100394669-e64ae500-3035-11eb-8f81-7b26c601af29.PNG)

**Comment by vimanyu** [comment] 2020-11-30 18:36
Hi @st4rdog,
Thanks for creating the issue. By default, Verbose Logging should be turned off (which I confirmed by firing up Unity 2020 and 2019 with our auth quickstart unity example). It would be great to reproduce this locally on my end for faster debugging. Here are the steps I performed on my box,

1. Launch quickstart unity "auth" example with Unity 2019 and Unity 2020.
2. Install FirebaseAuth 6.16.1 unity plugin.
3. Ensure Verbose Logging is "Off" by default in Assets -> External Dependency Manager -> Android Resolver -> Settings
4. Install IronSource Unity Plugin (tried with both including and excluding EDM4U updates)
5. Verbose Logging is still "Off" in the Settings Dialog.

Are there any other steps you are performing on your end that I missed here?

**Comment by st4rdog** [comment] 2020-12-07 23:52
I haven't had time to look into it much, but it may actually be something to do with [Google Play Games plugin](https://github.com/playgameservices/play-games-plugin-for-unity) being in the project. It must be something on their end, so this can probably be closed.

**Comment by vimanyu** [comment] 2020-12-08 00:29
Thanks for responding. Am closing this ticket for now as we couldn't reproduce it locally but please feel free to create a new ticket if you notice this again.

**Closed by vimanyu** 2020-12-08 00:29 UTC
Labels: needs-attention
