### ISSUE TITLE
[FR] Checkbox to remove jcenter in settings

### ISSUE THREAD

**Issue by hendri-voodoo** [googlesamples/unity-jar-resolver#439] opened 2021-05-31 12:34 UTC
### Feature proposal

* EDM4U Component: Android Resolver to have a checkbox to choose to omit jcenter from the repository list or not.

The sunsetting of Jcenter and Bintray  will definitely bring a significant impact to the android developer community. 

Some developers are trying early to check and remove their jcenter from their unity project. And in the current version, EDM are always adding the jcenter repo in the list of repository. 

It would be great if we can have a checkbox in android settings to omit the jcenter repo from the list of repository in gradle. So we can start to check whether removing jcenter completely will impact our games or not.

**Comment by hendri-voodoo** [comment] 2021-06-07 08:26
so are this going to be included in new release?

**Comment by viviskas** [comment] 2021-06-22 05:18
Duplicate of 

>      ####@#``

**Comment by siberder** [comment] 2021-09-16 11:37
Bump
jcenter is unreachable more and more often

**Comment by josesanchezng** [comment] 2021-09-17 09:26
jcenter should not be used anymore. Can this get fixed?

**Comment by troy-lamerton** [comment] 2021-12-29 12:15
These are the places where unity-jar-resolver uses `jcenter()` inside the Unity project:

`jcenter()` added to `mainTemplate.gradle`:

- https://github.com/googlesamples/unity-jar-resolver/blob/v1.2.168/source/AndroidResolver/src/PlayServicesResolver.cs#L2169

`jcenter()` used to download aar files:

- https://github.com/googlesamples/unity-jar-resolver/blob/v1.2.168/source/AndroidResolver/scripts/download_artifacts.gradle#L73
- https://github.com/googlesamples/unity-jar-resolver/blob/v1.2.168/source/AndroidResolver/scripts/download_artifacts.gradle#L2524

**Comment by Str4tos** [comment] 2022-01-17 15:54
Hello. 
I use Unity 2020.3.18f with `com.android.tools.build:gradle:4.0.1` and i am getting resolve error from `mavenCentral()` on build.
```
Could not resolve all dependencies for configuration ':launcher:debugRuntimeClasspath'.
Could not determine artifacts for com.anyArtifactFromCentral:anyArtifact:12.9.0.0
Could not get resource 'https://jcenter.bintray.com/com/anyArtifactFromCentral/12.9.0.0/anyArtifact-12.9.0.0.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/anyArtifactFromCentral/12.9.0.0/anyArtifact-12.9.0.0.aar'.
Read timed out
```
I checked and it happens when `jcenter()` is declared before `mavenCentral()`.
For some reason I don't understand, MavenCentral stops working in this case.
When I move `mavenСentral()` declaration above `jcenter()` or remove `jcenter()` altogether, all dependencies are resolved without errors.

jcenter should be removed from `mainTemplate.gradle` in `project.repositories` scope and from `baseProjectTemplate.gradle` in `repositories` scope.

Please make it possible to disable the repository `jcenter()`.

Thanks.

**Comment by spacepluk** [comment] 2022-01-17 19:56
this is working for me

https://github.com/spacepluk/unity-jar-resolver/commit/39c847e771215274af613e49441f09c6c55eaaa0

**Comment by Str4tos** [comment] 2022-01-24 08:02
`jcenter()` removed in 1.2.169 release

**Comment by paulinon** [comment] 2022-01-24 08:09
Hi folks,

Version 1.2.169 has been released four days ago, and as mentioned by @Str4tos, it includes the removal of `jcenter()`. That being said, I'll be closing this for now.

**Closed by paulinon** 2022-01-24 08:09 UTC
Labels: type: feature request
