### ISSUE TITLE
[Bug] After clicking 'Resolve' and seeing 'resolution success,' but nothing happens.

### ISSUE THREAD

**Issue by erdarjen** [googlesamples/unity-jar-resolver#696] opened 2024-06-27 09:48 UTC
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2023.2.20f1
  * External Dependency Manager version: Version 1.2.181
  * Source you installed EDM4U: .unitypackage
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: LevelPlay Sdk
  * Platform you are using the Unity editor on: Windows

### [REQUIRED] Please describe the issue here:
Previously, Mobile Dependency Manager was installed. I was told on the Unity forums that I could solve the problem I was experiencing by using External Dependency. The problem was resolved. However, later, after clicking Resolve, I saw that it was successful without any delay, but the SDK features I was using were not working, which made me suspicious. I found that the Assets/Plugin/Android folder was empty. In short, the resolve button is not working at the moment.

#### Please answer the following, if applicable:
I am currently experiencing this issue continuously. I tried uninstalling and reinstalling, but the problem was not resolved. I even reinstalled the Mobile Dependency Resolver, but the issue persisted there as well.

What happened? How can we make the problem occur?
When I try to install the External Dependency Resolver without uninstalling the Mobile Dependency Resolver, the issue repeats itself. Both of my projects are currently in the same state. There are no error indications in the console.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

**Comment by argzdev** [comment] 2024-06-27 13:22
Hey @erdarjen, thanks for reaching out. Could you try [enabling auto-resolution](https://github.com/googlesamples/unity-jar-resolver?tab=readme-ov-file#auto-resolution)? This should monitors the dependencies you have in your project, and will trigger every time the dependency list changes. However, in case this does not work, could you try using the `Force resolve` via `Assets > External Dependency Manager > Android Resolver > Force Resolve`. 

Other than that, for us to further investigate this, could you provide steps for us to reproduce this behavior? Or if there's any chance you could provide a [minimal reproducible example](https://meta.stackoverflow.com/questions/366988/what-does-mcve-mean), it help speed up our investigation. Thanks!

**Comment by argzdev** [comment] 2024-06-27 16:35
Thanks for sharing these details, @erdarjen. According to the [Ironsource documentation](https://developers.is.com/ironsource-mobile/unity/unity-plugin/#step-2), It does seem this is working as intended, and the correct way to resolve the issue is via the manual resolve.
> Manual resolve
> - Go to: Assets → Mobile Dependency Manager → Android Resolver → Resolve

With that, I'll go ahead and close this thread.

**Closed by argzdev** 2024-06-27 16:35 UTC
Labels: type: question, needs-info
