### ISSUE TITLE
Resolver made a mistake in finding correct depenecies

### ISSUE THREAD

**Issue by AminSojoudi** [googlesamples/unity-jar-resolver#311] opened 2020-01-12 20:06 UTC
### Please fill in the following fields:
Unity editor version: 2019.1.8f1
Play Services Resolver version: 1.2.124
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): AndroidResolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): OneSignal, GameAnalytics
Platform you are using the Unity editor on (Mac, Windows, or Linux):  Windows
Platform you are targeting (iOS, Android, and/or desktop):  Android
Scripting Runtime (Mono, and/or IL2CPP): Mono

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
I have added OneSignal Unity Plugin and GameAnalytics Unity Plugin.
Here is what Resolver Created for me in mainTemplate.gradle
```
// Android Resolver Dependencies Start
    implementation 'com.android.support:appcompat-v7:27.1.1' // Assets/GameAnalytics/Editor/GameAnalyticsDependencies.xml:5
    implementation 'com.android.support:cardview-v7:[26.0.0, 27.2.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:7
    implementation 'com.android.support:customtabs:[26.0.0, 27.2.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:8
    implementation 'com.android.support:support-v4:[26.0.0, 27.2.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:6
    implementation 'com.google.android.gms:play-services-ads-identifier:15.0.1' // Assets/GameAnalytics/Editor/GameAnalyticsDependencies.xml:3
    implementation 'com.google.android.gms:play-services-base:[10.2.1, 12.1.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:3
    implementation 'com.google.android.gms:play-services-basement:15.0.1' // Assets/GameAnalytics/Editor/GameAnalyticsDependencies.xml:4
    implementation 'com.google.android.gms:play-services-location:[10.2.1, 12.1.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:5
    implementation 'com.google.firebase:firebase-messaging:[10.2.1, 12.1.0[' // Assets/OneSignal/Editor/OneSignalDependencies.xml:4
// Android Resolver Dependencies End
```

When I try to build the project it will throw error:
`  java.lang.RuntimeException: Duplicate class com.google.android.gms.common.api.internal.zzbr found in modules classes.jar (com.google.android.gms:play-services-base:12.0.1) and classes.jar (com.google.android.gms:play-services-basement:15.0.1)`

It's clear that Base &  Basement have conflict with each other  but Resolver did not solve that.

Thanks

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc) 100%

**Comment by paulinon** [comment] 2020-01-14 16:00
Hi @AminSojoudi thanks for filing this issue. Could you check if this issue persists when you use an updated version of the resolver (v. 1.2.135)? If it does, please provide the detailed steps in reproducing your issue.

**Comment by AminSojoudi** [comment] 2020-01-15 14:27
@paulinon yup, it still happens,
Steps to Reproduce:
1- Create GameAnalyticsDependencies.xml under /Assets/GameAnalytics/Editor with this content:
```
<dependencies>
    <androidPackages>
        <androidPackage spec="com.google.android.gms:play-services-ads-identifier:15.0.1" />
        <androidPackage spec="com.google.android.gms:play-services-basement:15.0.1"/>
        <androidPackage spec="com.android.support:appcompat-v7:27.1.1" />
    </androidPackages>
</dependencies>
```
2- Create OneSignalDependencies.xml under /Assets/OneSignal/Editor with this content:
```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-base:[10.2.1, 12.1.0[" />
    <androidPackage spec="com.google.firebase:firebase-messaging:[10.2.1, 12.1.0["/>
    <androidPackage spec="com.google.android.gms:play-services-location:[10.2.1, 12.1.0[" />
    <androidPackage spec="com.android.support:support-v4:[26.0.0, 27.2.0[" />
    <androidPackage spec="com.android.support:cardview-v7:[26.0.0, 27.2.0[" />  
    <androidPackage spec="com.android.support:customtabs:[26.0.0, 27.2.0[" />
  </androidPackages>
</dependencies>
```
3- Tick the `Custom Gradle Template` in Android Player Settings
4- try to build the project.

**Comment by paulinon** [comment] 2020-01-15 16:28
Hi @AminSojoudi thanks for providing the details for reproducing the issue. I've encountered the same error message as well. I have filed an internal bug regarding this. I'm not able to share any specific timelines, so I'll just leave this open.

**Comment by MartinGonzalez** [comment] 2020-02-13 15:15
Yes, we have the same issue and it's random, some pipelines fails, some succeed.
The `Duplicate class` error happened

**Comment by MartinGonzalez** [comment] 2020-02-13 17:42
Unity 2018.4.16f1
Play Resolver Version: 1.2.133.0

We cannot go back and use older versions because we are using Firebase 6.9.0 that has that Play Resolver version.

**Comment by MartinGonzalez** [comment] 2020-02-18 02:23
any news?

**Comment by stewartmiles** [comment] 2020-03-06 22:15
This is a duplicate of #243.  The workaround is to disable mainTemplate.gradle.

**Closed by stewartmiles** 2020-03-06 22:15 UTC
Labels: type: bug
