### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Sneirox** [googlesamples/unity-jar-resolver#462] opened 2021-08-31 04:57 UTC
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.17f1
  * External Dependency Manager version: _____
  * Source you installed EDM4U: facebook-unity-sdk-11.0.0.unitypackage (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: _____ (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Facebook (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: MX Linux 19.4 (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
Warning in console at startup Unity:
`Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogWarning (object)
GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:239)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:314)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:121)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser (string) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2314)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe (System.Action`1<bool>,bool,bool,bool) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1635)
GooglePlayServices.PlayServicesResolver/<ScheduleResolve>c__AnonStorey1E:<>m__3F () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1604)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1461)
GooglePlayServices.PlayServicesResolver:ScheduleResolve (bool,bool,System.Action`1<bool>,bool) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.PlayServicesResolver:AutoResolve (System.Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1134)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__47 () (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113)
Google.RunOnMainThread:ExecutePollingJobs () (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__A () (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction (System.Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll () (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)
`

#### Please answer the following, if applicable:
Sometime

**Comment by paulinon** [comment] 2021-08-31 09:28
Hi @Sneirox,

The cause of this issue is likely related to your Unity configuration. Take note that later versions of the editor usually require a minimum API version of 19. With that, it's recommended that you use OpenJDK and Android SDK installed through Unity Hub. If you would like to use your own, please make sure the required version is installed and set correctly in your Preferences > External Tools.

I'll be closing this for now. If the issue persists or if this solution doesn't suit your use case, let me know by providing the complete steps in replicating your issue.

**Closed by paulinon** 2021-08-31 09:28 UTC
Labels: type: question
