### ISSUE TITLE
Failed to checkout 'ProjectSettings\GvhProjectSettings.xml' when using Perforce

### ISSUE THREAD

**Issue by wuyuntao** [googlesamples/unity-jar-resolver#310] opened 2020-01-02 08:55 UTC
Unity editor version: 2019.3.0.f1
Play Services Resolver version: 1.2.133.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): Android Resolver, iOS Resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.): Firebase
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): iOS, Android
Scripting Runtime (Mono, and/or IL2CPP): Mono on Android, IL2CPP on iOS

Reproduce steps: Try Android resolver from editor menu.

`GvhProjectSettings.xml` does not seem to be a valid asset of VersionControl.Provider.

This might be duplicate with #275.

```
// return null
var asset = UnityEditor.VersionControl.Provider.GetAssetByPath("ProjectSettings/GvhProjectSettings.xml");

// throw ArgumentNullException exception
UnityEditor.VersionControl.Provider.Checkout("ProjectSettings/GvhProjectSettings.xml", UnityEditor.VersionControl.CheckoutMode.Exact);
```

Unity Log:
Failed to checkout ProjectSettings\GvhProjectSettings.xml (System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: assets[0]
  at (wrapper managed-to-native) UnityEditor.VersionControl.Provider.Internal_Checkout(UnityEditor.VersionControl.Asset[],UnityEditor.VersionControl.CheckoutMode,UnityEditor.VersionControl.ChangeSet)
  at UnityEditor.VersionControl.Provider.CheckCallbackAndCheckout (UnityEditor.VersionControl.AssetList assets, UnityEditor.VersionControl.CheckoutMode mode, UnityEditor.VersionControl.ChangeSet changeset) [0x0009b] in <83a73882c51c4602b3d34743827d03e7>:0 
  at UnityEditor.VersionControl.Provider.Checkout (System.String asset, UnityEditor.VersionControl.CheckoutMode mode, UnityEditor.VersionControl.ChangeSet changeset) [0x00014] in <83a73882c51c4602b3d34743827d03e7>:0 
  at UnityEditor.VersionControl.Provider.Checkout (System.String asset, UnityEditor.VersionControl.CheckoutMode mode) [0x00001] in <83a73882c51c4602b3d34743827d03e7>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <437ba245d8404784b9fbab9b439ac908>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <437ba245d8404784b9fbab9b439ac908>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0 
  at Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x001aa] in Z:\tmp\tmp.riOjn5twhd\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:555 
  at Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x00000] in Z:\tmp\tmp.riOjn5twhd\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:484 
  at Google.FileUtils.CheckoutFile (System.String path, Google.Logger logger) [0x00029] in Z:\tmp\tmp.D3TY3fsrzI\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\FileUtils.cs:309 .
UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:120)
Google.FileUtils:CheckoutFile(String, Logger) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/FileUtils.cs:330)
Google.ProjectSettings:<checkoutFile>m__1(String, Logger) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:382)
Google.ProjectSettings:Save() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:806)
Google.ProjectSettings:SetBool(String, Boolean, SettingsLocation) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:482)
Google.ProjectSettings:SetBool(String, Boolean) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/ProjectSettings.cs:494)
GooglePlayServices.SettingsDialog:set_UseJetifier(Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/SettingsDialog.cs:233)
GooglePlayServices.<GradleResolution>c__AnonStorey1:<>m__6(HashSet`1) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/GradleResolver.cs:427)
GooglePlayServices.<LabelAssets>c__AnonStoreyA:<>m__0() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2149)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by paulinon** [comment] 2020-01-09 17:45
Duplicate of #275

**Closed by paulinon** 2020-01-09 17:45 UTC
Labels: duplicate
