### ISSUE TITLE
Problem with Google Play Services 10.2.4

### ISSUE THREAD

**Issue by mtpabis** [googlesamples/unity-jar-resolver#47] opened 2017-05-03 20:47 UTC
There seem to be a problem with 10.2.4 - specifying e.g. LATEST play-services-ads causes the error

> Google.JarResolver.ResolutionException: Cannot find candidate artifact for com.google.android.gms:play-services-ads-lite:[10.2.4]

(note the extra brackets around version string)

Examination of *.pom dependency files from Android SDK reveal that 10.2.4 files indeed include those extra problematic brackets.

**Comment by stewartmiles** [comment] 2017-05-04 16:55
I believe this was supposed to be fixed by 92b67214aa8cec5372c787190161690461c543b7 which was pulled into build 1.2.17.

@rampara was 92b67214aa8cec5372c787190161690461c543b7 supposed to fix the issue for 10.2.4?

**Comment by rampara** [comment] 2017-05-04 22:27
Yep, that commit was meant to address this very issue.

**Comment by stewartmiles** [comment] 2017-05-04 23:15
@mtpabis could you see whether you can reproduce the problem with the latest version of the Jar Resolver?

**Comment by jaroslaw-weber** [comment] 2017-05-08 09:32
had the same problem today, but fixed (upgraded jar resolver version)

**Comment by stewartmiles** [comment] 2017-05-08 16:00
@jaroslaw-weber so your issue is fixed in 1.2.19.0?  Do you see #48 as well?  I was unable to reproduce it.

**Comment by mtpabis** [comment] 2017-05-22 19:21
Sorry it took that long - it seems fixed in the latest version.

**Closed** 2017-05-22 21:04 UTC
