### ISSUE TITLE
Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by Darkfeast** [googlesamples/unity-jar-resolver#300] opened 2019-11-15 11:52 UTC
### Please fill in the following fields:
Unity editor version: 
2019.2.10f1
Play Services Resolver version: 
1.2.79.0
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.):
android resolver
Plugins SDK in use (Firebase, Admob, Facebook, etc.):
"Tik Tok"
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Mac
Platform you are targeting (iOS, Android, and/or desktop): 
Android
Scripting Runtime (Mono, and/or IL2CPP):
IL2CPP

### Please describe the issue here:
when i import the TaurusX in Unity   ,and then I clicked the "Assets/play services resolver/android resolver/resolve" ,   the issue  occured

### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:298)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:120)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2221)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1593)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1562)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1421)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1575)
GooglePlayServices.PlayServicesResolver:ExecuteMenuResolve(Boolean) (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1784)
GooglePlayServices.PlayServicesResolver:MenuResolve() (at Z:/tmp/tmp.lDxf0Zsaxo/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1799)

**Comment by stewartmiles** [comment] 2019-12-04 17:19
Closing as a duplicate of #273

**Closed by stewartmiles** 2019-12-04 17:19 UTC
Labels: duplicate

**Comment by stewartmiles** [comment] 2019-12-04 22:40
@Darkfeast I noticed you're using a really old version of the Android Resolver.  I recommend you upgrade as this was fixed in 1.2.125 https://github.com/googlesamples/unity-jar-resolver/blob/master/CHANGELOG.md#version-12125---sep-23-2019
