### ISSUE TITLE
[Bug] iOS port process for the podfile creates a null reference exception.

### ISSUE THREAD

**Issue by JimmyDeemo** [googlesamples/unity-jar-resolver#431] opened 2021-03-26 16:51 UTC
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.20f1
  * External Dependency Manager version: 1.2.164
  * Source you installed EDM4U: Unity Package Manager (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: iOS Resolver (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Many inc.; Helpshift, Facebook, Tapjoy and various ad providers. (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
After building my project there are two NullReferenceExceptions in the console related to the resolver. They seem to stem from a HTTP Utility function and track back to [https://github.com/googlesamples/unity-jar-resolver/blob/822d341110f9ecf770f872fdad5f98cbb0531d8b/source/IOSResolver/src/IOSResolver.cs#L1930](https://github.com/googlesamples/unity-jar-resolver/blob/822d341110f9ecf770f872fdad5f98cbb0531d8b/source/IOSResolver/src/IOSResolver.cs#L1930).

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
100% for each iOS build.

What happened? How can we make the problem occur?
Started happening recently, unsure of the cause. I have attached the stacks to this ticket.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

I cannot share the project as it is a commercial codebase. I can try things other than moving to a higher version of unity other than the 2019 LTS branch. I would be happy for a workaround for this issue if you could tell me what might the cause be?

**Comment by JimmyDeemo** [comment] 2021-03-26 16:52
[null_ref_1.txt](https://github.com/googlesamples/unity-jar-resolver/files/6213250/null_ref_1.txt)
[null_ref_2.txt](https://github.com/googlesamples/unity-jar-resolver/files/6213251/null_ref_2.txt)

Forgot to attached the stacks.

**Comment by JimmyDeemo** [comment] 2021-03-26 16:53
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

I only deleted the section it asked. All the rest of the template is the same.

**Comment by JimmyDeemo** [comment] 2021-03-26 18:26
Please note; issue does not occur when I reverted to 1.2.162, so I suspect this has happened in 1.2.164 looking at the changelog summary.

**Comment by chkuang-g** [comment] 2021-03-29 21:14
@JimmyDeemo 

According to the log you provided, it seems to be caused by this call.
https://github.com/googlesamples/unity-jar-resolver/blob/822d341110f9ecf770f872fdad5f98cbb0531d8b/source/IOSResolver/src/IOSResolver.cs#L2078

This is an analytics event to report when Podfile generation started.  If you don't like this event, you can actually turn this off from iOS Resolver Settings. But I digressed.

Since we did not change anything to this event from `1.2.162` to `1.2.164`, I suspect this is a regression from https://github.com/googlesamples/unity-jar-resolver/commit/3fb0e7b5f30d1f5e14d6267cd19df38c944f5c45.

As a workaround, I would recommend you to simply turn off `Enable Analytics Reporting` in iOS Resolver settings. (This is a shared setting for all analytics reporting in EDM4U)

**Comment by chkuang-g** [comment] 2021-03-29 22:09
Hmm...Oddly I was not able to reproduce the issue on my machine.

And reading through code, I am not sure what can cause the `NullReferenceException`.
https://github.com/googlesamples/unity-jar-resolver/blob/822d341110f9ecf770f872fdad5f98cbb0531d8b/source/VersionHandlerImpl/src/EditorMeasurement.cs#L518-L534

@JimmyDeemo Could you turn on the `Verbose Logging` in `iOS Resolver Setting`, and send us your editor log after you make an iOS build?

**Comment by chkuang-g** [comment] 2021-03-29 23:02
When I did a search for `HttpEncoder.GetCustomEncoderFromConfig() NullReferenceException`, [many](https://stackoverflow.com/questions/16922952/system-nullreferenceexception-object-reference-not-set-to-an-instance-of-an-obj) pointed out to use following way to solve this exception, which actually does not work with Unity.
```
HttpEncoder.Current = HttpEncoder.Default;
```

[System.Web.Util.HttpEncoder](https://docs.microsoft.com/en-us/dotnet/api/system.web.util.httpencoder.default?view=netframework-4.8) class does not exist in Unity `2019.4.9f1` or `2019.4.23f1`, which are the versions I used, yet it showed up in your log from Unity `2019.4.20f1`. This indicated that Unity does not fully implemented `System.Web.Util.HttpEncoder` in .NET 4.5, but to keep it as an internal class.

Also this Unity bugtracker.
https://issuetracker.unity3d.com/issues/httputility-null-reference-exception-on-net-4-dot-x-when-performing-httputility-dot-urlencode

This gives me an impression that this is a bug in Unity (or the mono which Unity includes).

I guess what we can do is to utilize [UnityEngine.Networking.UnityWebRequest.EscapeURL](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/Networking.UnityWebRequest.EscapeURL.html) instead of `HttpUtility.UrlEncode` when it is available in 2017.3.  Really prefer not to tie to Unity API since Unity can change this API at anytime.

For workaround, I have 2 suggestions:

1. Upgrade Unity. In the bugtracker, the issue is fixed in `2021.2.X`. _Hopefully_ they retroactively fix this in the latest version of `2019` or `2020`.
2. Downgrade Unity. Let me know if you still experience this issue in `2019.4.9f1`
3. Basically turn off Analytics, as I mentioned in https://github.com/googlesamples/unity-jar-resolver/issues/431#issuecomment-809718832. This will plague analytics from Firebase as well.  So make sure to turn off that one under `Windows > Firebase > Documentation` and scroll all the way to the bottom

Let me know if this helps.

**Comment by chkuang-g** [comment] 2021-03-30 18:11
Another thing we can do is probably try to catch exception like this during event reporting so that it will not break the rest of resolution process.

**Comment by JimmyDeemo** [comment] 2021-04-06 07:59
Sorry for my lack of response, I have been on annual leave.

I think, in the first instance, I will disable Analytics. I very much agree that event reporting shouldn't halt the rest of the resolution process. Unfortunately changing the major Unity verions to 2020 isn't an option for me right now, likewise with downgrading on the 2019 line.

**Comment by chkuang-g** [comment] 2021-04-24 01:28
No problem.  That is reasonable.
For workaround, please just turn off Analytics for both EDM4U and Firebase.
- Analytics settings for EDM4U can be found under `Assets > External Dependency Manager > Version Handler > Settings`
- Analytics settings for Firebase can be found under `Windows > Firebase > Documentation` at the very bottom.

Appreciate you approved to let us collect usage data before. Since this is causing usability issue, please just turn it off for now.

**Closed** 2021-04-28 20:24 UTC
Labels: type: bug
