### ISSUE TITLE
"Resolution failed" due to Dependencies were automatically modified to package:+

### ISSUE THREAD

**Issue by rchallenger** [googlesamples/unity-jar-resolver#183] opened 2019-01-25 13:58 UTC
I've added [IronSourceDependencies](https://raw.githubusercontent.com/googleads/googleads-mobile-unity/master/mediation/IronSource/source/plugin/Assets/GoogleMobileAds/Editor/IronSourceMediationDependencies.xml) to my Unity project and got error after resolving dependencies.  Console messages are given below.

So the question is how to forse keep version of androidPackage while solving conflicts during resolution process? And how to solve this issue win a generic way (wtihout magic in dependency file or locking version of androidPackage)? I'm sure it works somehow for others.

PS: In dependency file of IronSource there are two differen repositories and the main demand is to keep versions synchroniced, thay have to be the same for both packages. And if resolver sets dependency version to "+" it will take latest SDK version, though there will be no adapter with the same version.

> #### warning message:
> Some conflicting dependencies were found.
> The following dependency versions were modified:
> com.ironsource.sdk:mediationsdk:6.7.11 --> com.ironsource.sdk:mediationsdk:+

> #### error message:
> Failed to fetch the following dependencies:
> com.ironsource.sdk:sdk5:+

<details>
<summary>AndroidResolverDependencies.xml</summary>

```xml
<dependencies>
  <packages>
    <package>com.android.support:support-v4:26.1+</package>
    <package>com.google.ads.mediation:ironsource:6.7.11.0</package>
    <package>com.google.android.gms:play-services-ads:15.0.1</package>
    <package>com.ironsource.sdk:mediationsdk:6.7.11</package>
  </packages>
  <files>
    <file>Assets/Plugins/Android/android.arch.core.common-1.0.0.jar</file>
    <file>Assets/Plugins/Android/android.arch.lifecycle.common-1.0.0.jar</file>
    <file>Assets/Plugins/Android/android.arch.lifecycle.runtime-1.0.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.customtabs-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-annotations-26.1.0.jar</file>
    <file>Assets/Plugins/Android/com.android.support.support-compat-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-core-ui-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-core-utils-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-fragment-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-media-compat-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.android.support.support-v4-26.1.0.aar</file>
    <file>Assets/Plugins/Android/com.google.ads.mediation.ironsource-6.7.11.0.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-base-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-identifier-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-ads-lite-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-basement-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.google.android.gms.play-services-gass-15.0.1.aar</file>
    <file>Assets/Plugins/Android/com.ironsource.sdk.mediationsdk-6.8.1.jar</file>
  </files>
</dependencies>
```
</details> 
<br/>
Unity 2018.2.20
<br/>
Resolver 1.2.99.0
<br/>
GoogleAds 3.15.1

**Comment by rchallenger** [comment] 2019-01-25 13:59
PPS: path to package in warning and error messages is different, maybe it matters?

**Comment by stewartmiles** [comment] 2019-01-25 20:58
@rchallenger glancing at the error it looks like the reference package failed to fetch as it (i.e `com.ironsource.sdk:sdk5`) doesn't exist.  See https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/mediationsdk/

**Comment by rchallenger** [comment] 2019-01-28 06:59
> @stewartmiles
it looks like the reference package failed to fetch

Any way, even if it fails, my dependencies xml does not contain such a refference. 
**Here is the main question: where did it take it from?**

> @apautrot
I have a com.ironsource.sdk.mediationsdk-6.8.1.jar file as expected

The same happens in my case:

> @rchallenger
it will take latest SDK version, though there will be no adapter with the same version.

But the goal is to keep versions of SDK and adapter the same. SDK usually receive some updates which are not included in adapter. So to avoid some crashes or ANRs it is better not to mix these two libraries with different versions.

**Comment by apautrot** [comment] 2019-01-28 07:13
Resolving again this morning makes the resolver stuck. Taking a look at the gradle daemon log, I can see that the resolve still fails and goes into an infinite resolving attempt loop.

    Resolve failed due to com.ironsource.sdk:sdk5:unspecified missing for com.ironsource.sdk:mediationsdk:6.7.11, attempted to use com.ironsource.sdk:sdk5:unspecified, failed due to org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve com.ironsource.sdk:sdk5:unspecified.

Hope this could help finding the issue.

**Comment by apautrot** [comment] 2019-01-28 08:33
I have commented out the XML tag <androidPackages> in IronSourceMediationDependencies.xml, and also removed anything related in ProjectSettings/AndroidResolverDependencies.xml.

I have put com.google.ads.mediation.ironsource-6.7.11.0.aar & com.ironsource.sdk.mediationsdk-6.8.1.jar in a separate folder, to integrate them by hand.
Just like I already do for some other libraries, like chartboost.jar (the chartboost SDK library, to be integrated by hand alongside the mediation plug-in provided by admob).

But anytime I resolve, those files are removed in the process. Is there a kind of cache or a mechanism that explain why those files I'm now integrating by hand are kept being removed in the process ?
Are they referenced somewhere else ? Are they automatically recognized ? I have commented out IronSourceMediationDependencies.xml that references/declare them, but why are they removed ? Is there something I've missed here ?

I'm stuck with no workaround.
Can you please help us on finding a solution, a least temporarily ?

**Comment by apautrot** [comment] 2019-01-28 09:36
I finally found what kept them in the process : files are labeled 'Gpsr' under Unity (Asset Labels, at bottom of inspector), which is used by the PlayServicesResolver.
Exited Unity, edited the .meta by hand (when Unity is running the labels are automatically reassigned, I guess by the PlayServiceResolver).
Then I've been able to Resolve without those files to be touched.

**Comment by rchallenger** [comment] 2019-01-28 09:59
Great, but it doesn't solve the issue mentioned here. The purpose of Resolver is to hanlde jar and aar import and version conflicts. Though simple plugin dependency with certain version mentioned there is not handled correctly and due to some conflicting dependencies, not related to this package, its version changes in pack with other packages to "LATEST" so Resolver improts package of version I didn't need and at the end it tells that resolution failed.

PS: Of course I've imported those libraries manually and it worked. 
But what went wrong with Resolver here? 
Why did it take non existing package?

> com.ironsource.sdk:sdk5:+

**Comment by apautrot** [comment] 2019-01-28 10:05
The workaround I found is to do the integration by hand.

1) I commented out the XML tag \<androidPackages\> in file IronSourceMediationDependencies.xml

2) I put the libraries
* com.google.ads.mediation.ironsource-6.7.11.0.aar
* com.ironsource.sdk.mediationsdk-6.8.1.jar
is a separate folder.

4) I cleaned the file ProjectSettings/AndroidResolverDependencies.xml of any reference to those packages & files.

3) I removed the Asset Label 'Gpsr' that PlayServiceResolver put on those 2 libraries under Unity so the files aren't kept in the PlayServiceResolver process and kept being deleted (I had to exit Unity and edit the .meta by hand).

I agree, it's not a solution, just a temporary workaround.
But I have to move on.

Regards.

**Comment by stewartmiles** [comment] 2019-01-28 22:08
@rampara FYI sounds like IronSourceDependencies distributed in AdMob is causing issues for some users, could someone on the Ads team take a look?

**Comment by stewartmiles** [comment] 2019-01-29 16:42
@apautrot and @rchallenger looking at iron source's POM e.g https://dl.bintray.com/ironsource-mobile/android-sdk/com/ironsource/sdk/mediationsdk/6.5.0/ it looks like the problem is that they have a reference to `com.ironsource.sdk:sdk5` i.e

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.ironsource.sdk</groupId>
  <artifactId>mediationsdk</artifactId>
  <version>6.5.0</version>
  <dependencies>
    <dependency>
      <groupId>Android-SSP-unit-testing-develop-release-master-branches</groupId>
      <artifactId>mediationsdk</artifactId>
      <version>unspecified</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>Android-SSP-unit-testing-develop-release-master-branches</groupId>
      <artifactId>sdk5</artifactId> .  <!-- This references a non-existent artifact -->
      <version>unspecified</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by mariome17** [comment] 2019-01-31 09:48
I'm having the exact same issue.
@stuartmiles: many thanks for figuring out the root cause. I wrote to ironSource about this issue, included this discussion as a reference.

**Comment by stewartmiles** [comment] 2019-05-04 23:32
Everyone, I'm closing this out as it looks like a problem with IronSource's artifacts.

**Closed by stewartmiles** 2019-05-04 23:32 UTC
Labels: help wanted

**Comment by apautrot** [comment] 2019-05-05 07:45
Yes they have fixed the issue on their side.
[Duplicate of googleads-mobile-unity issue #807, resolved.](https://github.com/googleads/googleads-mobile-unity/issues/807)
