### ISSUE TITLE
The specified path is not of a legal form (empty)

### ISSUE THREAD

**Issue by UncleJey** [googlesamples/unity-jar-resolver#356] opened 2020-04-14 05:06 UTC
```
Stopped polling job due to exception: System.ArgumentException: The specified path is not of a legal form (empty).
  at System.IO.Path.InsecureGetFullPath (System.String path) [0x00025] in <567df3e0919241ba98db88bec4c6696f>:0 
  at System.IO.Path.GetFullPath (System.String path) [0x00000] in <567df3e0919241ba98db88bec4c6696f>:0 
  at Google.VersionHandlerImpl.get_EnabledEditorDllsLoaded () [0x0001c] in Z:\tmp\tmp.OifwP30d8k\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\VersionHandlerImpl.cs:2353 
  at Google.VersionHandlerImpl+<NotifyWhenCompliationComplete>c__AnonStorey0.<>m__0 () [0x00000] in Z:\tmp\tmp.OifwP30d8k\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\VersionHandlerImpl.cs:2386 
  at Google.RunOnMainThread.ExecutePollingJobs () [0x0004a] in Z:\tmp\tmp.OifwP30d8k\third_party\unity\unity_jar_resolver\source\VersionHandlerImpl\src\RunOnMainThread.cs:409 
UnityEngine.Debug:LogError(Object)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.OifwP30d8k/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:412)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1() (at Z:/tmp/tmp.OifwP30d8k/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.OifwP30d8k/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at Z:/tmp/tmp.OifwP30d8k/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.OifwP30d8k/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)

```

**Comment by UncleJey** [comment] 2020-04-14 05:08
from time to time self - throws exception

**Comment by stewartmiles** [comment] 2020-04-14 15:16
Duplicate of #358 353

**Comment by stewartmiles** [comment] 2020-04-14 15:17
We'll close this on the next release.

**Closed** 2020-04-17 15:09 UTC
Labels: duplicate, type: bug
