### ISSUE TITLE
[Question] How to reason about resolution failed error log?

### ISSUE THREAD

**Issue by feyil** [googlesamples/unity-jar-resolver#455] opened 2021-07-27 18:45 UTC
* Unity editor version: 2020.1.17f
  * External Dependency Manager version: 1.2.165
  * Source you installed EDM4U: _____ (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: Android Resolver
  * Plugins SDK in use: _____ (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac M1

Hi,

I was trying to resolve android dependencies for a unity project but in my team some of the guys can be able resolve the dependencies successfully but some not. Problem is I can not reason about the problem. Does anyone can help me about what to check. In my case I was getting below error log message:

Resolution failed
Failed to fetch the following dependencies:
com.adcolony:sdk:4.4.1
com.chartboost:chartboost-sdk:8.2.0
com.fyber.vamp:core-sdk:7.8.1
com.fyber.vamp:mopub-custom-events-5.13:7.8.1
com.fyber.vamp:mraid-kit:7.8.1
com.fyber.vamp:video-kit:7.8.1
com.ironsource.sdk:mediationsdk:7.1.0.2
UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey9:<>m__0(Boolean, String)
GooglePlayServices.<ResolveUnsafe>c__AnonStorey9:<>m__4()
Google.RunOnMainThread:ExecuteNext()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean)
GooglePlayServices.GradleResolver:ProcessAar(String)
GooglePlayServices.<ProcessAars>c__AnonStoreyB:<>m__0()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAllUnnested>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:332)

**Comment by paulinon** [comment] 2021-07-28 10:06
Hi @feyil,

In order to ensure you have the latest bug fixes and updates, could you try using version 1.2.166 of the resolver and see if this makes a difference? If the issue persists, please provide the steps needed to replicate this behavior.

**Comment by feyil** [comment] 2021-07-28 17:06
with latest version 1.2.166 I have tried and result below:

Resolution failed

Failed to fetch the following dependencies:
com.adcolony:sdk:4.4.1
com.chartboost:chartboost-sdk:8.2.0
com.fyber.vamp:core-sdk:7.8.1
com.fyber.vamp:mopub-custom-events-5.13:7.8.1
com.fyber.vamp:mraid-kit:7.8.1
com.fyber.vamp:video-kit:7.8.1
com.ironsource.sdk:mediationsdk:7.1.0.2


UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1055)
GooglePlayServices.GradleResolver:LogMissingDependenciesError(List`1) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:95)
GooglePlayServices.<DoResolutionUnsafe>c__AnonStorey18:<>m__22(List`1) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:912)
GooglePlayServices.<GradleResolution>c__AnonStorey11:<>m__17() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:375)
GooglePlayServices.<GradleResolution>c__AnonStorey11:<>m__27() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:440)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1115)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:541)
Google.RunOnMainThread:RunAction(Action) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested(Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:PollOnUpdateUntilComplete(Func`1, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:379)
GooglePlayServices.PlayServicesResolver:LabelAssets(IEnumerable`1, Action`1, Boolean, Action`2, Boolean, Boolean) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/PlayServicesResolver.cs:2319)
GooglePlayServices.GradleResolver:ProcessAar(String) (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1417)
GooglePlayServices.<ProcessAars>c__AnonStorey1B:<>m__24() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/AndroidResolver/src/GradleResolver.cs:1085)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:409)
Google.RunOnMainThread:<ExecuteAllUnnested>m__12() (at /Users/chkuang/Workspace/Git/unity-jar-resolver/source/VersionHand<message truncated>

I'm not sure how you can reproduce without getting the project or may be the machine, I have teammate with the same configuration and machine can able to resolve but somehow i cant. We both use the same source repo. When we compare we cant catch the difference.

Yesterday, I have imported com.adcolony:sdk:4.4.1 and mopub to the empty project and I can able to resolve android dependencies. However not in the original project.

**Comment by paulinon** [comment] 2021-07-29 13:23
Hi @feyil,

Could you try uploading your project in a private repository here in GitHub and add me as a collaborator so that we can identify the cause of this behavior?

**Comment by feyil** [comment] 2021-07-30 05:46
Hi,

Because of the privacy policies I cant do that. However, If you can lead me about possible causes of the problem I may check them.

**Comment by paulinon** [comment] 2021-07-30 09:14
Hi @feyil,

It would be easier for us to identify the cause of your issue if I could get a hold of a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project. In the meantime, could you try if updating your Unity editor to its latest version makes a difference?

Also, when you said that your teammate has the same configuration and machine as yours, does this mean that they are using a Mac M1 machine as well?

**Comment by feyil** [comment] 2021-08-02 05:30
Hi,

I think, I will not continue to spend time to debug it for now. I would love to prepare a minimal reproducible example, but project is not a small one and probably it will take significant amount of time and iteration. Also because of the current state of the project we cant directly update to latest version of the unity.

Yes, indeed. They are identical M1s.

**Comment by paulinon** [comment] 2021-08-02 13:56
Thanks for letting me know, @feyil. With that, I'll be closing this ticket for now. 

In the event that you wish to continue to debug this issue, let me know by replying to this thread.

**Closed by paulinon** 2021-08-02 13:56 UTC
Labels: needs-attention, type: question
