### ISSUE TITLE
Failed to determine the most recently installed Android SDK version.

### ISSUE THREAD

**Issue by jdelange** [googlesamples/unity-jar-resolver#298] opened 2019-11-13 18:06 UTC
Unity version 2019.2.12f1 installed through hub. Uninstalled previous version .11f1 first through hub. Windows.

Playservices 0.10.05

All was working before but something got messed up apparently.

Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogWarning(Object)
GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:239)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:252)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:121)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2240)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1621)
GooglePlayServices.<ScheduleResolve>c__AnonStorey1E:<>m__3F() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1590)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1449)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1603)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1124)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__47() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1103)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__18() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:303)

**Comment by jdelange** [comment] 2019-11-13 18:17
Trying to build the above (API level set to 28) using IL2CPP gives following error:

> UnityException: Android SDK not found Unable to locate Android SDK.
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

SDK and NDK were installed together with Unity Editor using hub. SDK is located at: 

> C:\Program Files\Unity\Hub\Editor\2019.2.12f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK

Which is also listed under Edit\preferences (Adroid SDK Tools installed with Unity (recommended), which holds the following path:

> C:/Program Files/Unity/Hub/Editor/2019.2.12f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK

**Comment by stewartmiles** [comment] 2019-12-04 17:19
Closing as a duplicate of #273

**Closed by stewartmiles** 2019-12-04 17:19 UTC
Labels: duplicate
