### ISSUE TITLE
[Bug] External Dependency Manager fails to resolve the MetaAudienceNetwork dependencies.

### ISSUE THREAD

**Issue by Davidnovarro** [googlesamples/unity-jar-resolver#642] opened 2023-09-21 11:48 UTC
### [REQUIRED] Please fill in the following fields:
  * Unity version: 2022.3.10f1
  * External Dependency Manager version: 1.2.177
  * Plugins SDK in use: Google Mobile Ads Unity plugin version v8.5.2
  * Platform: UnityEditor Android build
  * Mediation ad networks used, and their versions: IronSource-2.3.1, UnityAds-3.8.0, AppLovin-6.9.1, MetaAudienceNetwork-3.11.0

Apparently when I add MetaAudienceNetwork-3.11.0 Admob adapter  External Dependency Manager fails to resolve.
Here is the console error message:
```
Resolution failed
Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10
```

#### Steps to reproduce:
Download the demo project
[https://drive.google.com/file/d/1raDeZt11w3lO7tl8L-OHIi1TWwYlfoUq](https://drive.google.com/file/d/1raDeZt11w3lO7tl8L-OHIi1TWwYlfoUq)
Try to resolve the dependencies:
Assets > External Dependency Resolver > Android Resolver > Force Resolve

**Comment by paulinon** [comment] 2023-09-21 12:52
Hi @Davidnovarro,

Could you try if enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings resolves the issue? The generated files can handle the resolution better than the custom script in the resolver.

If that doesn't work, does enabling the Jetifier option in Android Resolver settings make any difference?

**Comment by Davidnovarro** [comment] 2023-09-21 17:29
> Hi @Davidnovarro,
> 
> Could you try if enabling both Custom Main Gradle Template and Custom Gradle Properties Template from your Player Settings > Publishing Settings resolves the issue? The generated files can handle the resolution better than the custom script in the resolver.
> 
> If that doesn't work, does enabling the Jetifier option in Android Resolver settings make any difference?

Hello, it is impossible for me to enable a custom Custom Gradle files because they cause other build issues.
Jetifier option is already enabled.

**Comment by paulinon** [comment] 2023-09-29 10:59
Thanks for the update, @Davidnovarro. The resolution failed on my end as well, but different dependencies appeared in the error message. Could you provide the error message you encountered when building the app so we can identify what's causing this to happen?

**Comment by Davidnovarro** [comment] 2023-10-04 04:11
> Thanks for the update, @Davidnovarro. The resolution failed on my end as well, but different dependencies appeared in the error message. Could you provide the error message you encountered when building the app so we can identify what's causing this to happen?

I've already provided

```
Resolution failed
Failed to fetch the following dependencies:
org.jetbrains.kotlin:kotlin-bom:1.8.10
```

**Comment by paulinon** [comment] 2023-10-05 17:46
Hi @Davidnovarro,

Apologies for the misundertanding. I meant the error message that appears after trying to build when Custom Main Gradle Template and Custom Gradle Properties Template are enabled. Enabling both of them is a common solution whenever there's an issue with resolving dependencies, so if this step fits your use case, it could be something worth looking at.

**Comment by Davidnovarro** [comment] 2023-10-06 15:25
> Hi @Davidnovarro,
> 
> Apologies for the misundertanding. I meant the error message that appears after trying to build when Custom Main Gradle Template and Custom Gradle Properties Template are enabled. Enabling both of them is a common solution whenever there's an issue with resolving dependencies, so if this step fits your use case, it could be something worth looking at.

Hi, in that case the build finishes without any issues.
But I don't think that enabling Custom Main Gradle Template is a good solution to this issue :|

**Comment by paulinon** [comment] 2023-10-06 17:24
Hi @Davidnovarro,

There may be another solution that's more suitable for your case, but based on the scenario you described, the resolver is exhibiting its intended behavior. 

I see that there's a similar [issue](https://github.com/googleads/googleads-mobile-unity/issues/2943) filed in another repository that's currently under investigation. That said, I'll be closing this ticket for now. Let me know if an issue arises with the resolver.

**Closed by paulinon** 2023-10-06 17:24 UTC
Labels: type: question, needs-attention
