### ISSUE TITLE
Usage is error prone with reflection calls, Proposed strongly typed solution.

### ISSUE THREAD

**Issue by prime31** [googlesamples/unity-jar-resolver#51] opened 2017-05-15 06:32 UTC
Currently, Jar Resolver requires some pretty ugly and unmaintainable reflection calls to get things working. What I have done personally is create a simple class that hides all the reflection and lets you use a strongly typed, easy to read/maintain API to access Jar Resolver.

An example usage of the API is below. It is more clear, less error prone and easier on the eyes than the [SampleDependencies](https://github.com/googlesamples/unity-jar-resolver/blob/0ab833b0b61f5b0d7f14d3a71752ae62282e46cd/sample/Assets/PlayServicesResolver/Editor/SampleDependencies.cs).

```csharp
[InitializeOnLoad]
public class PlayGameServicesDependencies : AssetPostprocessor
{
	static PlayGameServicesDependencies()
	{
		JarResolver.createSupportInstance( typeof( PlayGameServicesDependencies ).Name )
			.dependOn( "com.google.android.gms", "play-services-games", "9+", new string[] { "extra-google-m2repository" } )
			.dependOn( "com.google.android.gms", "play-services-plus", "9+", new string[] { "extra-google-m2repository" } );
	}
}
```

The code for the class is below. If this is something that you would like to have in the repo let me know and I can send over a pull request. If not, feel free to close this issue.

```csharp
namespace Google
{
	public class JarResolver
	{
		public class JarResolverImpl
		{
			object _svcSupport;

			public JarResolverImpl()
			{}


			public JarResolverImpl( object svcSupport )
			{
				_svcSupport = svcSupport;
			}


			public JarResolverImpl DependOn( string group, string artifact, string version, string[] packageIds = null, string[] repositories = null )
			{
				if( _svcSupport != null )
				{
					Google.VersionHandler.InvokeInstanceMethod( _svcSupport, "DependOn",
						new object[] { group, artifact, version },
						namedArgs: new Dictionary<string, object>()
						{
							{ "packageIds", packageIds },
							{ "repositories", repositories }
						});
				}

				return this;
			}
		}


		public static JarResolverImpl CreateSupportInstance( string clientName )
		{
#if !UNITY_ANDROID
			// if we arent on Android default to an empty instance
			return new JarResolverImpl();
#endif

			// bail out with an empty instance if the PlayServicesSupport class isnt available
			var playServicesSupport = Google.VersionHandler.FindClass( "Google.JarResolver", "Google.JarResolver.PlayServicesSupport" );
			if( playServicesSupport == null )
				return new JarResolverImpl();

			// create a live instance of the PlayServicesSupport class and return a live JarResolverImpl wrapping it
			var svcSupport = Google.VersionHandler.InvokeStaticMethod( playServicesSupport, "CreateInstance",
				new object[] {
				clientName,
				EditorPrefs.GetString( "AndroidSdkRoot" ),
				"ProjectSettings"
			} );

			return new JarResolverImpl( svcSupport );
		}
	}
}

```

**Comment by stewartmiles** [comment] 2017-05-15 16:03
The reason we have this reflection ugliness in place is that we end up with a way to run the VersionHandler to select the appropriate version of the PlayServicesResolver package when multiple plugins all pull in different versions.

Adding the shim that brings back static typing sounds like a great idea.  How would we handle multiple versions of the shim though if the interface changes?

e.g if a user includes plugin A with PlayServicesResolver version X and plugin B with PlayServicesResolver version Y, where version X has a newer interface than Y?

**Comment by prime31** [comment] 2017-05-15 16:40
I could be mistaken but isn't the situation of having multiple versions of Jar Resolver no longer possible? When I add the unitypackage it renames the DLLs removing the version number from them (i.e. Google.IOSResolver_v1.2.21.0.dll gets renamed to Google.IOSResolver.dll). Perhaps that only happens with a clean install though.

I suppose this could be solved in much the same way as the current wrapper works by adding an optional assemblyName parameter to the CreateSupportInstance method that just defaults to "Google.JarResolver".

**Comment by stewartmiles** [comment] 2017-05-15 17:10
That's true that VersionHandler will pick the latest revision of the
package.

I think the issue is that if we add multiple instances of the same file e.g
JarResolverImpl-a.b.c.cs and JarResolverImpl-a.b.d.cs we'll end up with
duplicate definitions of the interface where Unity will simply bail out
with a compile error.  AFAIK you can't disable compilation of source files
using metadata in Unity - though I could be wrong ...  an alternative I
guess would be to mark up the source code in these files with "#if ENABLED"
and have the VersionHandler modify the appropriate file(s) to enable them.
WDYT?

**Comment by prime31** [comment] 2017-05-15 17:29
Is it necessary to have multiple versions of the same source file here? If the interface changes can't we just add a new method signature to match and mark the old was as Obsolete? Hmm. I guess technically that would cause issues if a user installs a plugin with version n + 1 and then installs version n on top of it. Unity is pretty terrible about file management when adding unitypackages so anything could happen in that situation.

Going with a compiler wrapper could work but it might cause more problems than it's worth trying to deal with changing source files and getting Unity to recompile them and all that fun. Perhaps this solution is better left out of the official repo and folks can be left to make something similar on their own if they want it.

**Comment by stewartmiles** [comment] 2017-05-15 17:33
Yeah I know.  Perhaps adding a version to the each interface filename is
enough for the moment.  e.g JarResolverImpl-1.2.3.cs should be pretty clear
that it's older than JarResolverImpl-1.2.5.cs .  We could start with
something like that and if users are totally confused we'll take a look at
other options.

WDYT?

**Comment by prime31** [comment] 2017-05-15 20:05
That could work. Do you foresee the underlying API changing often (mainly the PlayServicesSupport.CreateInstance and DependOn methods)? If they will remain pretty static that should work just fine.

**Comment by stewartmiles** [comment] 2017-05-15 20:07
It's always changing at the moment.  TBH we've been talking about moving to
a json config file instead of having an API you need to call.  That would
be a bit more concise and more future proof - but - of course - not
statically typed.

I'm cool with adding a shim impl layer for the moment, if you want to send
a pull request we can get this going.

BTW: Is prime31 using the IOSResolver component as well or just the Jar
Resolver?

**Comment by prime31** [comment] 2017-05-15 20:24
JSON config files would be quite nice and they would save having to write any code at all to set things up.

For the pull request, what would you like the main class to be called (in the snippet I posted it is the Google.JarResolver class)? Maybe Google.JarResolver.Resolver or is that too redundant?

We do not use the IOSResolver at all. iOS doesn't have the dependency nightmares of Android so I've never actually seen a case where it would be required ;)

**Comment by stewartmiles** [comment] 2017-05-15 20:29
Oh iOS most definitely has dependency nightmares of it's own.  We're
already dealing with this using Cocoapods to try to get a handle on it
across just Google's plugins.  When it comes to 3rd party plugins they drop
in frameworks at random versions which can conflict with ours so it's still
very much a pain.  If you guys don't have any frameworks that are shared,
then I completely understand that you wouldn't need Cocoapods support.

w.r.t the Jar Resolver class, yeah Google.JarResolver.Resolver seems
reasonable to me.  In the typical use case I would assume someone would
do...

using Google.JarResolver;

Resolver.blah
Resolver.stuff
Resolver.etc

Cheers,
Stewart

**Comment by prime31** [comment] 2017-05-15 20:46
On the iOS side we've only got one shared framework and it is internal so we don't run into any issues there luckily ;)

I'll go with Google.JarResolver.Resolver for the PR then. Should I stick `ClearDependencies` in the shim as well? I don't personally use it nor do I know when someone would want to use it from the outside but perhaps there are folks who do use it somewhere...

**Comment by stewartmiles** [comment] 2017-05-15 20:59
No I don't think we need to expose ClearDependencies, the only place I
think we're using it is in the very limited unit tests we have in place.

Thanks!

**Closed** 2017-05-23 17:03 UTC
