### ISSUE TITLE
Failed to determine the most recently installed Android SDK version

### ISSUE THREAD

**Issue by aldiazj** [googlesamples/unity-jar-resolver#268] opened 2019-09-02 23:24 UTC
I had this error on Unity 2019.2.3f1

Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogError(Object)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion()
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion()
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean)
GooglePlayServices.<ScheduleResolve>c__AnonStorey6:<>m__0()
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob()
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8()
Google.RunOnMainThread:ExecutePollingJobs()
Google.RunOnMainThread:<ExecuteAll>m__1()
Google.RunOnMainThread:RunAction(Action)
Google.RunOnMainThread:ExecuteAll()
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by stewartmiles** [comment] 2019-09-07 00:58
Duplicate of #260

**Closed by stewartmiles** 2019-09-07 00:58 UTC
