### ISSUE TITLE
New Jar resolver removes Play Services library

### ISSUE THREAD

**Issue by fertigo** [googlesamples/unity-jar-resolver#212] opened 2019-05-13 10:14 UTC
Because I encountered a crash in Firebase Remote Config when running version 1.2.102 of Play Services resolver  (which updated some of the libraries) I decided to try an upgrade the resolver.

The new version (1.2.111) deleted all Play Services libraries but didn't install the new ones although it says "Resolution succeeded". So result is a project without Play Services libraries (which off course won't build)

I didn't change any other thing than updating the resolver (*Dependencies.xml files didn't change).

When running in the editor I get an error message (though I don't know if this causes the issue): 

System.NullReferenceException: Object reference not set to an instance of an object
  at Google.VersionHandler.InvokeMethod (System.Type type, System.Object objectInstance, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x00054] in Z:\tmp\tmp.7eOCFUaXh7\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:506 
  at Google.VersionHandler.InvokeStaticMethod (System.Type type, System.String methodName, System.Object[] args, System.Collections.Generic.Dictionary`2[TKey,TValue] namedArgs) [0x00000] in Z:\tmp\tmp.7eOCFUaXh7\third_party\unity\unity_jar_resolver\source\VersionHandler\src\VersionHandler.cs:481 
  at Facebook.Unity.Editor.AndroidSupportLibraryResolver.setupDependencies () [0x00034] in <10e3a2e9d4094bf5b9409184a698ff5e>:0 
  at Facebook.Unity.Editor.AndroidSupportLibraryResolver..cctor () [0x00000] in <10e3a2e9d4094bf5b9409184a698ff5e>:0

**Comment by stewartmiles** [comment] 2019-05-13 14:57
@fertigo if you're seeing `System.NullReferenceException` with the callstack pointing back to Facebook it looks like you're using an old version of the VersionHandler.dll not the version released in 1.2.111.  You can verify the installed version of each DLL in this plugin by navigating to `Assets > Play Services Resolver > PLUGIN_NAME > Settings`, it should be shown at the top of the window.

**Comment by fertigo** [comment] 2019-05-13 15:44
Thanks Stewart. I did check this one and I do have the latest version (see attachments).. Still getting this error and a Play resolver that only removes Play Services libraries but doesn't ad them.. 


![Screenshot 2019-05-13 at 17 42 39](https://user-images.githubusercontent.com/3536249/57634992-9bc65c80-75a6-11e9-8c8f-e959080d805d.png)


![Screenshot 2019-05-13 at 17 39 55](https://user-images.githubusercontent.com/3536249/57634862-69b4fa80-75a6-11e9-89a8-3081c6070eb4.png)

**Comment by stewartmiles** [comment] 2019-05-13 15:59
Have you tried restarting Unity?

The line referenced by the exception is definitely suggesting that an old version of the VersionHandler plugin is running.

Old code (exception makes sense):
https://github.com/googlesamples/unity-jar-resolver/blob/ea3e8d815e6d0148af87ece3deefdb9be6b2dc1f/source/VersionHandler/src/VersionHandler.cs#L506

New code (exception line makes no sense):
https://github.com/googlesamples/unity-jar-resolver/blob/e71269b2b7391efa72fe9675f706376f11a1e123/source/VersionHandler/src/VersionHandler.cs#L506

**Comment by fertigo** [comment] 2019-05-14 06:58
Problem solved. I had to close Unity. Delete Unity Library and PlayServicesResolver folders. Restart Unity and import the resolver again. Then it worked. 

I think deleting the library folder did the trick...

Thanks for your help!

**Comment by cra0zy** [comment] 2019-05-20 14:46
I'm getting the exact same error, except deleting the folders above did not do the trick.

**Comment by chkuang-g** [comment] 2019-05-20 23:29
Hi @cra0zy,

If you share the exact the same callstack, you can update to the latest Firebase SDK, which comes with the latest Unity Jar Resolver, and do what @fertigo suggested.  

Otherwise, please provide more information about the error you saw.

Shawn

**Comment by fertigo** [comment] 2019-05-21 05:47
With another project we had the problem that the new resolver removed Play
Services libraries, but didn't add the new versions. To solve this we had
to remove one of the *dependencies.xml files. Then resolve. Then put it
back again and resolve again.

Willem

Op di 21 mei 2019 om 01:29 schreef chkuang-g <notifications@github.com>:

**Comment by cra0zy** [comment] 2019-05-21 07:41
@chkuang-g its literally the exact same thing as the OP, I can't provide any more useful info that the OP has not yet provided.

@fertigo Interesting, will try that!

**Comment by cra0zy** [comment] 2019-05-21 12:37
Hmm, turns out if the custom mainTemplate.gradle is enabled, the resolved does no longer download the deps but instead just adds `complie 'lib'` instead.

PS. Should use `implementation`, `compile` has been deprecated for quite some time now.

**Comment by chkuang-g** [comment] 2019-05-22 01:09
@cra0zy 
This is the intended behavior.
When using mainTemplate.gradle, it no longer needs to add Android libraries to the Unity project.
So it will remove them and use Gradle to download them as part of the build process.

@stewartmiles

**Comment by matie** [comment] 2019-05-22 06:53
> @cra0zy
> This is the intended behavior.
> When using mainTemplate.gradle, it no longer needs to add Android libraries to the Unity project.
> So it will remove them and use Gradle to download them as part of the build process.
> 
> @stewartmiles

With the new intended behaviour, we are one step back, because we need to disable the auto resolver and manually enable it now and then.

We are using plugins (ad networks) which conflicts with the android arch cycle runtime lib. There is no option found by us removing these issues. Only preventing them to be added by the resolver helps. Therefore there is no option to automatically resolve android. 

How to work around this with the current version;

1. Disable custom gradle
2.Force resolving android libs
3.Disable auto resolving android libs
4.Run export
5.Add libs to custom gradle
6.Enable custom gradle.

If someone from google/unity picks up the ongoing issues and make it work in stead of a struggle, I will sent them definitively flowers with a large box of chocolates!


Cheers.
Mathijs.

**Comment by stewartmiles** [comment] 2019-05-22 15:55
@matie this will be resolved when the patch for https://github.com/googlesamples/unity-jar-resolver/issues/210 is in.  You'll be able to disable the gradle patching.

**Comment by stewartmiles** [comment] 2019-05-22 23:53
Fixed by a61a3c3d0120932224ff5832f9bd1058c33b02a5

**Closed by stewartmiles** 2019-05-22 23:53 UTC
Labels: bug
