### ISSUE TITLE
[Bug] EDM4U Always change `GvhProjectSettings.xml` Although I Have A FULL SETTINGS!

### ISSUE THREAD

**Issue by CodeMasterYi** [googlesamples/unity-jar-resolver#579] opened 2022-12-02 07:56 UTC
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity Sample](https://github.com/firebase/quickstart-unity/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: Unity2021.3.14f1
  * External Dependency Manager version: 1.2.175
  * Source you installed EDM4U: UPM (.unitypackage or Unity Package Manager)
  * Features in External Dependency Manager in use: ALL (Android Resolver, iOS Resolver, VersionHandler, etc.)
  * Plugins SDK in use: Firebase,Admob,Facebook,Adjust,ApplovinMax (Firebase, Admob, Facebook, etc.)
  * Platform you are using the Unity editor on: Mac, Targeting Android Platform (Mac, Windows, or Linux)

### [REQUIRED] Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
As title, EDM4U often change the xml file when I change C# script and go back to Unity.
There always be a popup that prompts `Auto resolution`. (Every Time, I click disable!)

#### Please answer the following, if applicable:
What's the issue repro rate? (eg 100%, 1/5 etc)
1/4

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Actually, I dont know how to reproduce it.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

My Full Configured XML
```
<?xml version="1.0" encoding="utf-8"?>
<projectSettings>
  <projectSetting name="com.google.external-dependency-managerAnalyticsEnabled" value="False" />
  <projectSetting name="com.google.firebaseAnalyticsEnabled" value="False" />
  <projectSetting name="Google.IOSResolver.AutoPodToolInstallInEditor" value="True" />
  <projectSetting name="Google.IOSResolver.CocoapodsIntegrationMethod" value="2" />
  <projectSetting name="Google.IOSResolver.PodfileAddUseFrameworks" value="True" />
  <projectSetting name="Google.IOSResolver.PodfileAllowPodsInMultipleTargets" value="True" />
  <projectSetting name="Google.IOSResolver.PodfileAlwaysAddMainTarget" value="True" />
  <projectSetting name="Google.IOSResolver.PodfileEnabled" value="True" />
  <projectSetting name="Google.IOSResolver.PodfileStaticLinkFrameworks" value="True" />
  <projectSetting name="Google.IOSResolver.PodToolExecutionViaShellEnabled" value="True" />
  <projectSetting name="Google.IOSResolver.PodToolShellExecutionSetLang" value="True" />
  <projectSetting name="Google.IOSResolver.SwiftFrameworkSupportWorkaroundEnabled" value="True" />
  <projectSetting name="Google.IOSResolver.SwiftLanguageVersion" value="5.0" />
  <projectSetting name="Google.IOSResolver.VerboseLoggingEnabled" value="True" />
  <projectSetting name="Google.PackageManagerResolver.Enable" value="True" />
  <projectSetting name="Google.PackageManagerResolver.PromptToAddRegistries" value="True" />
  <projectSetting name="Google.PackageManagerResolver.PromptToMigratePackages" value="True" />
  <projectSetting name="Google.PackageManagerResolver.VerboseLoggingEnabled" value="True" />
  <projectSetting name="Google.VersionHandler.CleanUpPromptEnabled" value="True" />
  <projectSetting name="Google.VersionHandler.RenameToCanonicalFilenames" value="False" />
  <projectSetting name="Google.VersionHandler.RenameToDisableFilesEnabled" value="True" />
  <projectSetting name="Google.VersionHandler.VerboseLoggingEnabled" value="True" />
  <projectSetting name="Google.VersionHandler.VersionHandlingEnabled" value="True" />
  <projectSetting name="GooglePlayServices.AndroidPackageInstallationEnabled" value="True" />
  <projectSetting name="GooglePlayServices.AutoResolutionDisabledWarning" value="True" />
  <projectSetting name="GooglePlayServices.AutoResolveOnBuild" value="True" />
  <projectSetting name="GooglePlayServices.AutoResolverEnabled" value="False" />
  <projectSetting name="GooglePlayServices.ExplodeAars" value="True" />
  <projectSetting name="GooglePlayServices.LocalMavenRepoDir" value="Assets/GeneratedLocalRepo" />
  <projectSetting name="GooglePlayServices.PatchAndroidManifest" value="True" />
  <projectSetting name="GooglePlayServices.PatchMainTemplateGradle" value="True" />
  <projectSetting name="GooglePlayServices.PatchPropertiesTemplateGradle" value="True" />
  <projectSetting name="GooglePlayServices.PromptBeforeAutoResolution" value="False" />
  <projectSetting name="GooglePlayServices.UseGradleDaemon" value="False" />
  <projectSetting name="GooglePlayServices.UseJetifier" value="True" />
  <projectSetting name="GooglePlayServices.VerboseLogging" value="True" />
</projectSettings>
```

And It always want to change it to
```
<?xml version="1.0" encoding="utf-8"?>
<projectSettings>
  <projectSetting name="Google.IOSResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.PackageManagerResolver.VerboseLoggingEnabled" value="False" />
  <projectSetting name="Google.VersionHandler.VerboseLoggingEnabled" value="False" />
  <projectSetting name="GooglePlayServices.AutoResolverEnabled" value="False" />
  <projectSetting name="GooglePlayServices.PromptBeforeAutoResolution" value="False" />
</projectSettings>
```

**Comment by CodeMasterYi** [comment] 2022-12-06 04:07
I mean EMD4U always automatically change my previous settings(full settings after I click every "ok" button in every EDM4U setting panel)
I dont want EDM4U change it!

**Comment by CodeMasterYi** [comment] 2022-12-06 04:10
@paulinon I dont think the issue should be closed now~

**Comment by CodeMasterYi** [comment] 2022-12-06 08:57
![image](https://user-images.githubusercontent.com/10430162/205865901-e34f9f43-8873-41b8-97bc-174a315a7c64.png)

It changes again.

**Comment by paulinon** [comment] 2022-12-06 13:07
Thanks for the clarification, @CodeMasterYi. Let me see if I could replicate this on my end. In order to identify what's causing this, could you provide the SDKs (with their respective versions) that you imported for your implementation?

**Comment by CodeMasterYi** [comment] 2022-12-07 01:35
Unity Plugin version:
EDM4U 1.2.175 (import via .tgz file)
Facebook 14.1.0
Firebase(Core, Crashlytics, Analytics) 10.1.1 (import via .tgz files)
Applovin Max 5.5.5
Adjust (I dont know which version we imported, and I cant find any vesion file in it)

**Comment by paulinon** [comment] 2022-12-07 17:21
Hi @CodeMasterYi,

It seems that the behavior described here is similar to what's in #524. The team is currently investigating the cause of the issue. That said, I'll be closing this for now, and you may refer to the original thread for any updates.

**Comment by paulinon** [comment] 2022-12-07 17:22
Duplicate of #524

**Closed by paulinon** 2022-12-07 17:21 UTC
Labels: type: question, needs-attention
